# FUNDING.yml for Rhodium.js

github: [Spiri0]         # GitHub Sponsors account(s)
#ko_fi: spiri0             # Ko-fi username
#buy_me_a_coffee: spiri0   # Buy Me a Coffee username

# Optional: add other platforms if needed
# patreon: spiri0patreon
# open_collective: spiri0collective
# liberapay: spiri0
# custom: ['https://mycustomlink1.com', 'https://mycustomlink2.com']
